package {{packageName}}.gateway;

import io.quarkus.runtime.Quarkus;
import io.quarkus.runtime.annotations.QuarkusMain;

/**
 * Mod-PL/SQL Web Gateway Application.
 * <p>
 * This application serves as a replacement for Oracle's mod_plsql Apache module,
 * routing HTTP requests to PostgreSQL PL/pgSQL procedures that generate HTML
 * using HTP/HTF compatibility functions.
 * <p>
 * Generated by orapgsync.
 */
@QuarkusMain
public class GatewayApplication {

    public static void main(String... args) {
        Quarkus.run(args);
    }
}
